#!/bin/sh

DEVEL_ROOT=$HOME/Entwicklung

ln -s $DEVEL_ROOT/libFSKDecoder/FSKDecoder.h FSKDecoder.h
ln -s $DEVEL_ROOT/libFSKDecoder/FSKDecoderOptions.h FSKDecoderOptions.h
ln -s $DEVEL_ROOT/libFSKDecoder/FSKDecodedText.h FSKDecodedText.h
ln -s $DEVEL_ROOT/libFSKDecoder/libFSKDecoder.a libFSKDecoder.a
